In [10]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [4]:
arr1[2]

3

In [5]:
arr1[2] = 5

In [6]:
arr1

array([1, 2, 5])

In [8]:
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [11]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1, 0])

3
3
3
4


In [12]:
arr3 = np.array(['India', 'China', 'USA', 'Mexico'])
print(arr3)


['India' 'China' 'USA' 'Mexico']


In [45]:
arr3[1]

'China'

In [38]:
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [40]:
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [44]:
arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.80565922 0.62930837]


[[0.95474411 0.07380502 0.50035885 0.16137571]
 [0.53950341 0.93668017 0.74362063 0.99365739]
 [0.74089438 0.12585272 0.56590852 0.79586153]]


In [46]:
print(np.full((4,6), 10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [48]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [50]:
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [51]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
arr = np.random.rand(5,5)
print(arr)

[[0.62302678 0.96452545 0.20163428 0.14850188 0.83067416]
 [0.42089937 0.66112101 0.59023028 0.05668868 0.02881334]
 [0.07920853 0.32537022 0.99370531 0.44236459 0.74356937]
 [0.75931113 0.22982618 0.06197978 0.62899184 0.03658951]
 [0.37837866 0.67651737 0.77213562 0.86078655 0.97817332]]


In [55]:
print(np.sum(arr, axis = 0))

[2.26082447 2.85736023 2.61968526 2.13733353 2.6178197 ]


In [56]:
print(np.sum(arr, axis=1))

[2.76836255 1.75775266 2.58421802 1.71669844 3.66599151]


In [58]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.4997209273649286
0.5902302761539863
0.3204996496358138
0.10272002541667939


In [59]:
arr = np.random.rand(5,5)
print(arr)

[[0.90148673 0.69083925 0.73150911 0.79402026 0.84221659]
 [0.13444437 0.08274373 0.13407687 0.68320831 0.53356858]
 [0.76654612 0.91222311 0.79926668 0.53008029 0.15897519]
 [0.3674771  0.62612952 0.8307418  0.61071326 0.45594493]
 [0.14599892 0.03959163 0.2352699  0.30732333 0.39351628]]


In [60]:
print(np.sort(arr, axis=1))

[[0.69083925 0.73150911 0.79402026 0.84221659 0.90148673]
 [0.08274373 0.13407687 0.13444437 0.53356858 0.68320831]
 [0.15897519 0.53008029 0.76654612 0.79926668 0.91222311]
 [0.3674771  0.45594493 0.61071326 0.62612952 0.8307418 ]
 [0.03959163 0.14599892 0.2352699  0.30732333 0.39351628]]


In [61]:
arr = np.array([4,5,6,7])

In [62]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [63]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [65]:
arr2 = np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [74]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8],[5,6,7,8]])


In [75]:
cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [76]:
cat = np.concatenate((arr1,arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
